### ISSUE TITLE
Respect meta.json order

### ISSUE THREAD

**Issue by Kikobeats** [shuding/nextra-theme-docs#3]
<img width="790" alt="Screen Shot 2020-09-28 at 12 01 01" src="https://user-images.githubusercontent.com/2096101/94418908-4f22f780-0182-11eb-88a5-e9cbd62d275b.png">

I'm trying to set up a custom order for my docs files; I thought order is important but looks a different order is considered.

In that case, I want to set up "Welcome" as the first entry.

Any tips for doing that?

**Comment by shuding** [comment]
There's a typo `"Templates": "templates"` in your meta.json, which should be `"templates": "Templates"`. If a route is undefined in the config it will show up at the very top :D

**Comment by Kikobeats** [comment]
🤦 thanks @shuding!
